# SwiftLint Configuration for IMDUMB

# Paths to include during linting
included:
  - IMDUMB

# Paths to ignore during linting
excluded:
  - Pods
  - build
  - ArkanaKeys
  - fastlane

# Rules to disable
disabled_rules:
  - trailing_whitespace
  - todo
  - line_length

# Rules to enable
opt_in_rules:
  - empty_count
  - empty_string

# Rule configurations
type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

# Naming rules
identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
  excluded:
    - id
    - URL
    - url

reporter: "xcode"
